### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/Ognon#1]
- [ ] Tests unitaires
- [ ] Doc fiable de l'API
- [ ] Fixer des convention pour le code python. Qu'est sensé faire et ne pas faire un controller, un model, etc.
- [ ] Finir de bien commenter le code
- [ ] Revoir le fonctionnement du client (avec une approche plus PPO ?)
